services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: investmentDB
      DATABASE_URL: "mysql://root:password@db:3306/investmentDB"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 20s


  backend:
    build: ./backend 
    container_name: investment_backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/investmentDB"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app 
      - /app/node_modules 
    command: ["./wait-and-start.sh"]

  frontend:
    build: ./frontend 
    container_name: investment_frontend
    ports:
      - "3000:3000" 
    depends_on:
      - backend 
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    command: ["npm", "run", "dev"] 

volumes:
  db_data: